# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class VaultOpsKeys < Formula
  desc "Script to quickly view a pre-configured list of keys from an enterprise vault in"
  homepage "https://github.com/dotcomrow/vault-ops-keys"
  url "https://github.com/dotcomrow/vault-ops-keys/archive/v1.125.tar.gz"
  sha256 "c9b82d0155866ebdb63590ed82d8e90dc5c8c4b72b3e295becba666e70fad2af"

  depends_on "curl"
  depends_on "jq"
  depends_on "vault"

  def install
    bin.install "show-keys.sh" => "show-keys"
    prefix.install "files"
  end

  test do
    system "#{bin}/show-keys.sh", "--help"
  end
end
