# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class VaultOpsKeys < Formula
  desc "Script to quickly view a pre-configured list of keys from an enterprise vault in"
  homepage "https://github.com/dotcomrow/vault-ops-keys"
  url "https://github.com/dotcomrow/vault-ops-keys/archive/v1.121.tar.gz"
  sha256 "b490ba7f7499d36e4ef8de2f0cc6a503229a2014e4f2c3280a17d28553365288"

  depends_on "curl"
  depends_on "jq"
  depends_on "vault"

  def install
    bin.install "show-keys.sh" => "show-keys"
    prefix.install 'files'
  end

  test do
    system "#{bin}/show-keys.sh", "--help"
  end
end
