# typed: false
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class VaultOpsKeys < Formula
  desc "Script to quickly view a pre-configured list of keys from an enterprise vault in"
  homepage "https://github.com/dotcomrow/vault-ops-keys"
  url "https://github.com/dotcomrow/vault-ops-keys/archive/v1.124.tar.gz"
  sha256 "9aa208d3188e6edc44e22fe00d3cb93320a5eac36d97cced07ff92f8cbf43bc2"

  depends_on "curl"
  depends_on "jq"
  depends_on "vault"

  def install
    bin.install "show-keys.sh" => "show-keys"
    prefix.install "files"
  end

  test do
    system "#{bin}/show-keys.sh", "--help"
  end
end
